### ISSUE TITLE
例外処理

### ISSUE THREAD

**Issue by yasunobuigarashi** [mamix1116/owaranai-meter#34]
本来の趣旨から考えて想定外な状況なのを分かった上で、意地悪な実験として
男性４、女性０でスタートして
女性が発言していることにして、女性のボタンを押したら、女性のタイマーが進みました
人数が０のときはタイマーが進まないようにした方が自然かな、と思いました

**Comment by kaizumaki** [comment]
@yasunobuigarashi ご指摘感謝です！たしかに！そのパターンは見逃していました（人数フィールドのところしか気にしていなかった）。対応しますね。
