### ISSUE TITLE
inject された $api を使うようにする

### ISSUE THREAD

**Issue by MaySoMusician** [mamix1116/owaranai-meter#86]
`this.$axios` の代わりに `this.$api` を使う

`this.$api` は `frontend/plguins/api.ts` で `inject` された axios インスタンス

**Comment by kaizumaki** [comment]
取り急ぎ置き換えて、typeエラーは `@ts-ignore` で逃げました。後日対応してくれると助かります！ 🙏

**Comment by MaySoMusician** [comment]
@kaizumaki こちら対応しました！

**Comment by kaizumaki** [comment]
@MaySoMusician ありがとうございます！こちらのissueはクローズしますね。
